### ISSUE TITLE
Custom tracking fields do not work with Rails 3 (or Rails 4) w/o strong parameters

### ISSUE THREAD

**Issue by edslocomb** [ankane/searchjoy#21]
...which is probably correct behavior, but should definitely be added to the README.

The following line is where searchjoy prevents data from being written to custom columns:

https://github.com/ankane/searchjoy/blob/master/app/models/searchjoy/search.rb#L7

**Comment by ACPK** [comment]
https://github.com/ankane/searchjoy/issues/23

**Comment by ankane** [comment]
Support for `attr_accessible` will be removed in the next version, so going to close.
