### ISSUE TITLE
Can't mass-assign protected attributes for Searchjoy::Search: user_id, source

### ISSUE THREAD

**Issue by ACPK** [ankane/searchjoy#23]
When the application tries to save a search done via Searchkick, i get:

```
Can't mass-assign protected attributes for Searchjoy::Search: user_id, source
```

**Comment by ankane** [comment]
You should be able to create an initializer with:

```ruby
class Searchjoy::Search
  attr_accessible :search_type, :query, :results_count, :custom_field_1, :custom_field_2
end
```

**Comment by ACPK** [comment]
@ankane - Should the user_id attr_accessible be mentioned in the docs as it says it should just work with SearchKick?

**Comment by ankane** [comment]
Same as #21 - support for `attr_accessible` will be removed in the next version, so going to close.
