### ISSUE TITLE
Unused Eager Loading detected

### ISSUE THREAD

**Issue by Xosmond** [ankane/searchjoy#25]
Bullet is getting this on the searchjoy module:
/admin/searchjoy/searches/recent
Unused Eager Loading detected
  Searchjoy::Search => [:convertable]
  Remove from your finder: :includes => [:convertable]

Should you remove it? Im wrong?

**Comment by ankane** [comment]
Hey Jordano, thanks for reporting. That'll be the case when there are no conversions, but it's needed when there are conversions.
