### ISSUE TITLE
Index name too long SQLite

### ISSUE THREAD

**Issue by FranciscoCG** [ankane/searchjoy#30]
StandardError: An error has occurred, this and all later migrations canceled:

-- add_index(:searchjoy_searches, [:search_type, :normalized_query, :created_at], {:name=>"index_searchjoy_searches_on_search_type_and_normalized_query_an"})
rake aborted!

Index name 'index_searchjoy_searches_on_search_type_and_normalized_query_an' on table 'searchjoy_searches' is too long; the limit is 62

**Comment by ankane** [comment]
Thanks for reporting @FranciscoCG 👍  All fixed on master.
