### ISSUE TITLE
Rails API Only Support

### ISSUE THREAD

**Issue by Tybot204** [ankane/searchjoy#32]
I think a good addition to this gem would be Rails 5 API only support. As it stands now, this gem requires Sprockets and ActionView to be included in your project. I would love to be able to remove both from my application, as I use Searchjoy for tracking searches and conversions, but don't use the interface provided to view this information.

It would be an even bigger bonus if the option made the Searchjoy routes return JSON instead of an HTML page, but that can always be added at a later time.

**Comment by ankane** [comment]
Hey @Tybot204, Searchjoy doesn't depend on Sprockets, but one its dependencies does. I've updated Chartkick to remove the dependency: https://github.com/ankane/chartkick/commit/8708020c7159b2e0c81dbda29daefbc37fb8f7ab

Add this to your Gemfile and you should be good:

```ruby
gem "chartkick", github: "ankane/chartkick"
```
