### ISSUE TITLE
On Migration (index too long)

### ISSUE THREAD

**Issue by franciscopinheir** [ankane/searchjoy#35]
ArgumentError: Index name 'index_searchjoy_searches_on_convertable_id_and_convertable_type' on table 'searchjoy_searches' is too long; the limit is 62 characters

**Comment by ankane** [comment]
Hey @franciscopinheir, what database and version of Rails are you on?

**Comment by franciscopinheir** [comment]
sqlite3

**Comment by ankane** [comment]
Hey @franciscopinheir, which version of Rails?

**Comment by franciscopinheir** [comment]
Hi, sorry. 

Rails 5.1.5

**Comment by ankane** [comment]
All fixed https://github.com/ankane/searchjoy/commit/1f0f90ce7d81d0e84eb9bdbc48dae1c8d55dec32. Thanks @franciscopinheir 👍

**Comment by sanjaygir** [comment]
i am still getting this error. has this issue not been resolved yet?

**Comment by ankane** [comment]
Hey @sanjaygir, looks like another change broke it. Try master.

**Comment by sanjaygir** [comment]
hi @ankane . Thanks for a speedy reply. Currently i am using gem 'searchjoy' in my gemfile. Do i need to specify it differently in order to use master branch. Please guide. Thanks a lot!
