### ISSUE TITLE
Duplicate tracking when Searchkick execute => false

### ISSUE THREAD

**Issue by jfloff** [ankane/searchjoy#37]
I was debugging some tracking and found out that if I have a Searchkick query with `execute: false` and then later on, I use the multi search like this: `Searchkick.multi_search([query])` I got 3 entries on Searchjoy just from that one query.

**Comment by ankane** [comment]
Hey @jfloff, I added a test case for this and was also unable to reproduce manually. No search record is created with `execute: false`.

https://github.com/ankane/searchjoy/blob/bdeba4d73065966d9cb853c51c59e8b997a51a1c/test/searchjoy_test.rb#L47

**Comment by jfloff** [comment]
Hi there,

You are right, after you answer I was able to narrow it down a little bit more and found out that some actions are triggering multiple Searchjoy entries. This was more or less my test case:
```
products = Product.search("apples")
5.times do
    products.suggestions
end
```
This is creating 5 entries on Searchjoy.

**Comment by ankane** [comment]
Hey @jfloff, I'm not able to reproduce that either (with Searchjoy 0.3.2 and Searchkick 3 and 4). I just pushed a new version (Searchjoy 0.4.0) to add tracking to `Searchkick.multi_search`. If you're still having issues with the latest version, please create a PR a with a failing test case.
