### ISSUE TITLE
Multiple queries

### ISSUE THREAD

**Issue by refresco12** [ankane/searchjoy#4]
Is it possible to log a multiple queried search?  For example if someone has to choose a search term and a category.

**Comment by ACPK** [comment]
@ankane - Is it possible to use JSONB for this? We're adding Searchkick to four models each of which have their own filters. As such, the number of extra searchjoy fields could start to add up.

**Comment by ankane** [comment]
Yeah, you can add whatever fields you'd like to the model. https://github.com/ankane/searchjoy#track-searches
