### ISSUE TITLE
Fails with Sprockets 4.0.0 

### ISSUE THREAD

**Issue by kapso** [ankane/searchjoy#40]
Sprockets 4.0.0 was just released, and `rails assets:precompile` fails, but when I comment this gem, it works.

My environment -

- Rails 6.0.0
- Sprockets 4.0.0
- Ruby 2.6.5
- Searchjoy 0.4.1

**Comment by ankane** [comment]
Hey @kapso, thanks for reporting. Can you give master a shot?

**Comment by kapso** [comment]
@ankane yea `master` works, thanks for the quick fix.
