### ISSUE TITLE
exception from groupdate gem

### ISSUE THREAD

**Issue by lazybios** [ankane/searchjoy#41]
when click post button will report `wrong number of arguments (given 4, expected 2)`  exception from `groupdate` gem. 

![image](https://user-images.githubusercontent.com/1796906/76064484-b8fc6980-5fc4-11ea-888e-176b2f8716a6.png)

**Comment by ankane** [comment]
Hey @lazybios, thanks for reporting! Fixed on master.

**Comment by ankane** [comment]
Just released 0.4.3 with this fix.

**Comment by lazybios** [comment]
Cool @ankane 👍, thanks for quick fix.
