### ISSUE TITLE
How to use with autocomplete

### ISSUE THREAD

**Issue by apuntovanini** [ankane/searchjoy#42]
Hello @ankane, thanks as usual for your amazing work
A question: how would you suggest using searchjoy with autocomplete-as-you-type feature? Tracking each character is too much, maybe with a timeout? Something like 

```ruby
if user.searches.where('created_at > ?', 5.seconds.ago)
  # update search
else
  # search and track
end
```

**Comment by ankane** [comment]
Hey @apuntovanini, I haven't used search-as-you-type in a production environment, but that sounds like a good place to start. Let me know how it goes.

**Comment by apuntovanini** [comment]
For our specific needs in this case we decided to overwrite current session's last search

```ruby
if Searchjoy::Search.where(session_id: context[:session].id.to_s).where('created_at >= ?', Time.now - 30.seconds).any?
  search = Searchjoy::Search.where(session_id: context[:session].id.to_s).last
else
  search = Searchjoy::Search.new(
    session_id: context[:session].id.to_s,
    search_type: 'JobName',
    user_id: context[:current_user]&.id
  )
end
search.query = term
search.normalized_query = term.downcase
search.results_count = r.count
search.save
```

We return `search.id` to the frontend to store the conversion when user clicks to one of the suggestions we provide with Searchkick. We'll surely refine this, but right now it's already giving some good insights

**Comment by ankane** [comment]
Awesome, makes sense. Great to hear it's working.

**Comment by ankane** [comment]
Cleaning up issues. If there are any more learnings (either now or in the future), would love to hear them (just fyi).
