### ISSUE TITLE
User track with multiple models

### ISSUE THREAD

**Issue by DiegoOrejuela** [ankane/searchjoy#43]
Hi @ankane. Thanks for this gem!

I have several devise models on my app, and I want to save it in the search table regardless of the model. However I see that the migration does not have a polymorphic reference. I could solve this by enabling this option in the migration and overwriting the model according to the [Rails engines guide](https://guides.rubyonrails.org/engines.html#overriding-models-and-controllers). I've taken a look at the code and can't see where else the user relationship is used, in case something else needs to be overwritten. I would like to ask you if there is any special reason for not giving polymorphism support to the user that it may be bypassing. 

Thanks!

**Comment by ankane** [comment]
Hey @DiegoOrejuela, I think most apps will only have a single user model, which is why it's not polymorphic, but you should be able to add additional columns to the table.
