### ISSUE TITLE
Multiple conversions per search

### ISSUE THREAD

**Issue by cspeer** [ankane/searchjoy#45]
Hi,

is there a built-in way for searches to be able to convert more than once?
Right now, if I have Searchkick create the SearchJoy search via `track` and then call `.convert(model)` on that search, no other model can convert that search. But it makes sense for multiple search results to convert a single search. For example when I search for tortilla chips, I might not just add the unfavored version to the cart, but the spicy one as well ;-)

If there is no built-in way to do this with Searchkick & SearchJoy right now, I guess a possible workaround would be to not have Searchkick create any searches and only create a new search and convert it immediately once the actual conversion takes place.

**Comment by ankane** [comment]
Hey @cspeer, there's not a built-in way, but you can create a separate `search_conversions` table and insert a record in the same place where `.convert(model)` is called.

**Comment by cspeer** [comment]
Great, thanks a lot @ankane !

**Comment by ankane** [comment]
Just fyi, the next release will have [built-in support](https://github.com/ankane/searchjoy#multiple-conversions-unreleased) for this (with a `searchjoy_conversions` table).
