### ISSUE TITLE
Conversion tracking one-to-many query-to-conversions

### ISSUE THREAD

**Issue by zyqxd** [ankane/searchjoy#46]
Is one-to-many query-to-conversions supported ootb?

We're using searchkick and currently investigating if we should include searchjoy for conversion tracking. Our search has a one search many result behaviour pattern. 

It looks like by default searchkick creates the searchjoy record. Can we overwrite this behaviour easily? Possibly add a join table and move `convertable` poly assoc to there?

**Comment by ankane** [comment]
Hey @zyqxd, check out #45.

**Comment by zyqxd** [comment]
Ah, cool. I'll close this issue.

Is it safe to drop the `convertable_` columns on the search joy table? Assuming that I'll use a join table that will have this information? 

Also, I suppose this is a searchkick question; but I'm not sure how searchkick uses the `conversions` field for ranking. Could you let me know which file is the conversion ranking function declared? (I'm assuming there is one)

**Comment by ankane** [comment]
You'll want to keep the `convertable_` columns if you use the Searchjoy dashboard so it works (which will just show the first conversion).

The Searchkick conversion ranking code is [here](https://github.com/ankane/searchkick/blob/c8d887960e1f7076d00ea195da05f83ef965bb5c/lib/searchkick/query.rb#L616).

**Comment by ankane** [comment]
Just fyi, the next release will have [built-in support](https://github.com/ankane/searchjoy#multiple-conversions-unreleased) and allow you to drop the `convertable_` columns on searches.
