### ISSUE TITLE
Is it possible to use searchjoy with mongodb?

### ISSUE THREAD

**Issue by mdebo** [ankane/searchjoy#7]
Hi,

I'm using searchkick, postgresql as backend and a mongo database to store tracking datas.
So my question is: Is it possible to use searchjoy with mongo?

thanks

**Comment by jwachira** [comment]
@ankane Plan doing this with Redis or Mongodb? for speed

**Comment by ankane** [comment]
@jwachira I'm not, but feel free to create a port of it.

**Comment by williamweckl** [comment]
+1

**Comment by ankane** [comment]
Going to close, as there are no plans for this.
